[build]
  publish = "dist"
  command = "npm run generate"

[build.environment]
  NODE_VERSION = "8"
  YARN_VERSION = "1.5.1"
  YARN_FLAGS = "--no-ignore-optional"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
#    Content-Security-Policy = "default-src 'none'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'; script-src 'unsafe-inline'; style-src 'self'; object-src 'none'; font-src 'self';"
# minimal config due to some nuxt issues with csp
    Content-Security-Policy = "base-uri 'none'; form-action 'self'; frame-ancestors 'none'; object-src 'none'; font-src 'self';"

